CREATE TABLE `desaparecidos` (
  `id_interno` bigint NOT NULL AUTO_INCREMENT,
  `iddependenciaorigen` varchar(255) DEFAULT NULL,
  `IDvictimadirecta` varchar(255) DEFAULT NULL,
  `IDvinculacion` varchar(255) DEFAULT NULL,
  `IDreporte` varchar(255) DEFAULT NULL,
  `nombre` varchar(255) DEFAULT NULL,
  `primerapellido` varchar(255) DEFAULT NULL,
  `segundoapellido` varchar(255) DEFAULT NULL,
  `fechanacimiento` varchar(255) DEFAULT NULL,
  `Sexo` varchar(50) DEFAULT NULL,
  `edadActual` varchar(50) DEFAULT NULL,
  `dependenciaOrigen` varchar(250) DEFAULT NULL,
  `fechahechos` varchar(255) DEFAULT NULL,
  `fechapercato` varchar(255) DEFAULT NULL,
  `cantidadRegistros` varchar(255) DEFAULT NULL,
  `publicarficha` varchar(255) DEFAULT NULL,
  `estatusvictimadirecta` varchar(255) DEFAULT NULL,
  `EstatusVictima` varchar(255) DEFAULT NULL,
  `estado` varchar(255) DEFAULT NULL,
  `municipio` varchar(255) DEFAULT NULL,
  `ffechahechos` varchar(255) DEFAULT NULL,
  `ffechapercato` varchar(255) DEFAULT NULL,
  `fechacaptura` varchar(255) DEFAULT NULL,
  `fecha_insercion` datetime DEFAULT NULL,
  PRIMARY KEY (`id_interno`)
) ENGINE=InnoDB AUTO_INCREMENT=7441 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
